
server:
  port: 6001


eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:
      defaultZone: http://localhost:6002/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制
